import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule, FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { Router, RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-alta-vehiculo',
  standalone: true,
  imports: [ReactiveFormsModule, FormsModule, RouterModule, CommonModule],
  templateUrl: './alta-vehiculo.component.html',
  styleUrls: ['./alta-vehiculo.component.css']
})
export class AltaVehiculoComponent implements OnInit {
  vehiculoForm: FormGroup;
  loading = false;
  message = '';
  messageType: 'success' | 'error' = 'success';
  currentYear = new Date().getFullYear();
  createdVehicle: any = null;

  // Image and preview state
  imageUrls: string[] = [];
  imageUrlInput = '';
  previewVehicle: any = null;
  isVerified = false;

  // File upload state
  uploading = false;

  colorOptions = ['#000000', '#ffffff', '#b71c1c', '#0d47a1', '#1b5e20', '#ff9800', '#9c27b0', '#607d8b'];

  constructor(
    private fb: FormBuilder,
    private http: HttpClient,
    private router: Router
  ) {
    this.vehiculoForm = this.createForm();
  }

  ngOnInit(): void {}

  toggle0km(checked: boolean): void {
    this.vehiculoForm.get('es0km')?.setValue(checked);
    const kmControl = this.vehiculoForm.get('km');
    if (checked) {
      // 0 km: set km to 0 and disable the km control
      kmControl?.setValue(0);
      kmControl?.disable({ emitEvent: false });
      const stockControl = this.vehiculoForm.get('stock');
      if (!stockControl?.value || parseInt(stockControl?.value) <= 0) {
        stockControl?.setValue(1);
      }
    } else {
      // Re-enable km input when not 0 km
      kmControl?.enable({ emitEvent: false });
    }
  }

  selectColor(color: string): void {
    this.vehiculoForm.get('color')?.setValue(color);
  }

  createForm(): FormGroup {
    return this.fb.group({
      // idVehiculo is generated by the backend — not entered by the user
      marca: ['', [Validators.required]],
      modelo: ['', [Validators.required]],
      anio: ['', [
        Validators.required,
        Validators.min(1900),
        Validators.max(this.currentYear + 1)
      ]],
      precio: ['', [
        Validators.required,
        Validators.min(0.01)
      ]],
      km: ['', [
        Validators.required,
        Validators.min(0)
      ]],
      es0km: [false],
      stock: [1],
      color: ['#000000'],
      descripcion: ['']
    });
  }

  isFieldInvalid(fieldName: string): boolean {
    const field = this.vehiculoForm.get(fieldName);
    return field ? (field.invalid && (field.dirty || field.touched)) : false;
  }

  onSubmit(): void {
    // Prevent immediate send — use Verify step
    this.verify();
  }

  addImage(): void {
    const url = this.imageUrlInput?.trim();
    if (!url) return;
    this.imageUrls.push(url);
    this.imageUrlInput = '';
  }

  onFilesSelected(event: any): void {
    const files: FileList = event.target.files;
    if (files && files.length) this.uploadFiles(files);
    // reset input
    event.target.value = null;
  }

  async uploadFiles(files: FileList | File[]): Promise<void> {
    const arr = Array.from(files as FileList);
    if (arr.length === 0) return;
    this.uploading = true;

    const form = new FormData();
    arr.forEach(f => form.append('files', f));

    try {
      const res: any = await this.http.post('http://localhost:3001/api/upload', form).toPromise();
      if (res && res.success && res.files && res.files.length) {
        this.imageUrls.push(...res.files);
      }
    } catch (err) {
      console.error('Error subiendo archivos', err);
      this.message = 'Error subiendo imágenes';
      this.messageType = 'error';
    } finally {
      this.uploading = false;
    }
  }

  onDrop(ev: DragEvent): void {
    ev.preventDefault();
    if (ev.dataTransfer && ev.dataTransfer.files && ev.dataTransfer.files.length) {
      this.uploadFiles(ev.dataTransfer.files);
    }
  }

  onDragOver(ev: DragEvent): void {
    ev.preventDefault();
  }

  async onPaste(ev: ClipboardEvent): Promise<void> {
    const items = ev.clipboardData?.items;
    if (!items) return;
    const files: File[] = [];
    for (let i = 0; i < items.length; i++) {
      const item = items[i];
      if (item.kind === 'file') {
        const file = item.getAsFile();
        if (file) files.push(file);
      }
    }
    if (files.length) {
      await this.uploadFiles(files);
    }
  }

  removeImage(index: number): void {
    this.imageUrls.splice(index, 1);
  }

  focusImageInput(): void {
    const fileInput = document.querySelector('.dropzone input[type=file]') as HTMLInputElement | null;
    if (fileInput) fileInput.click();
  }

  verify(): void {
    if (!this.vehiculoForm.valid) {
      this.markAllFieldsAsTouched();
      this.isVerified = false;
      return;
    }

    // If 0km is checked, ensure stock > 0
    const es0 = this.vehiculoForm.get('es0km')?.value;
    if (es0) {
      const stock = parseInt(this.vehiculoForm.get('stock')?.value) || 0;
      if (stock <= 0) {
        this.message = 'Ingrese la cantidad de stock para vehículos 0 km';
        this.messageType = 'error';
        this.isVerified = false;
        return;
      }
    }

    const data = this.prepareFormData();
    // Include color and stock/es0km
    data.color = this.vehiculoForm.get('color')?.value;
    data.stock = this.vehiculoForm.get('stock')?.value || 0;
    data.es0km = this.vehiculoForm.get('es0km')?.value || false;

    // Prepare a preview object (id will be generated by backend)
    this.previewVehicle = { ...data };
    this.isVerified = true;

    // Scroll to preview
    setTimeout(() => {
      const el = document.getElementById('preview');
      if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }, 50);
  }

  register(): void {
    if (!this.previewVehicle) return;
    this.loading = true;
    this.message = '';

    this.http.post('http://localhost:3001/api/vehiculos', this.previewVehicle)
      .subscribe({
        next: (response: any) => {
          this.loading = false;
          if (response.success) {
            this.message = 'Vehículo registrado exitosamente';
            this.messageType = 'success';
            this.createdVehicle = response.vehiculo || null;
            // Clear form & preview
            this.vehiculoForm.reset();
            this.imageUrls = [];
            this.previewVehicle = null;
            this.isVerified = false;
          } else {
            this.message = response.message || 'Error al registrar el vehículo';
            this.messageType = 'error';
          }
        },
        error: (error) => {
          this.loading = false;
          console.error('Error en alta de vehículo:', error);

          if (error.status === 400) {
            this.message = error.error?.message || 'Datos inválidos';
          } else if (error.status === 500) {
            this.message = 'Error del servidor. Intente nuevamente.';
          } else {
            this.message = 'Error de conexión. Verifique su conexión a internet.';
          }
          this.messageType = 'error';
        }
      });
  }

  editar(): void {
    // Return to edit mode
    this.isVerified = false;
    setTimeout(() => this.focusImageInput(), 50);
  }

  private prepareFormData(): any {
    const formValue = this.vehiculoForm.value;

    // Use the controlled imageUrls array rather than a comma textarea
    const fotosArray = this.imageUrls.slice();

    return {
      marca: formValue.marca,
      modelo: formValue.modelo,
      anio: parseInt(formValue.anio),
      precio: Math.round(parseFloat(formValue.precio) * 100) / 100,
      km: parseInt(formValue.km),
      fotos: fotosArray,
      descripcion: formValue.descripcion || ''
    };
  }

  private markAllFieldsAsTouched(): void {
    Object.keys(this.vehiculoForm.controls).forEach(key => {
      const control = this.vehiculoForm.get(key);
      if (control) {
        control.markAsTouched();
      }
    });
  }

  limpiarFormulario(): void {
    this.vehiculoForm.reset();
    this.imageUrls = [];
    this.imageUrlInput = '';
    this.previewVehicle = null;
    this.isVerified = false;
    this.message = '';
    this.createdVehicle = null;
  }

  irInicio(): void {
    this.router.navigate(['/home']);
  }

  formatCurrency(amount: number): string {
    if (amount === null || amount === undefined || isNaN(amount)) return '';
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount);
  }
}